pub mod broker;
mod budget;
pub mod cli;
mod dedup;
pub mod doctor;
pub mod hook;
pub mod install;
pub mod local;
mod markup;
pub mod mcp;
pub mod metrics;
pub mod model;
mod normalize;
pub mod notes;
mod router;
pub mod session;
pub mod state;
pub mod summarizer;
pub mod upstream;
pub mod workspace;
