//! The context envelope every broker tool returns (schema `ripwire-broker.context/v1`).

use serde::Serialize;

pub const SCHEMA_VERSION: &str = "ripwire-broker.context/v1";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Status {
    Ready,
    AttentionRequired,
    Unknown,
}

impl Status {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Ready => "ready",
            Self::AttentionRequired => "attention_required",
            Self::Unknown => "unknown",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Intent {
    Orient,
    Symbol,
    Change,
    Debug,
    Docs,
    Review,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    Primary,
    Caller,
    Callee,
    Test,
    Config,
    Doc,
    Risk,
    /// Found only by the remote classifier (`--online`): a hypothesis, never a relation.
    Semantic,
}

/// Whether a statement is a fact reported by ripwire or a conclusion the broker drew.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Basis {
    Ripwire,
    BrokerInference,
    /// Generated by a local model from evidence in this envelope (PRD 10.3).
    LocalModel,
    /// A probability from the remote classifier (`--online`, D-063); never a fact.
    RemoteClassifier,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Source {
    pub verb: &'static str,
    pub basis: Basis,
}

impl Source {
    pub fn fact(verb: &'static str) -> Self {
        Self {
            verb,
            basis: Basis::Ripwire,
        }
    }
}

/// Repository text is data, never instructions (PRD 15.2).
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Untrusted {
    pub untrusted_repository_data: String,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Item {
    pub kind: &'static str,
    pub role: Role,
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    pub why_included: String,
    pub source: Source,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<Untrusted>,
    /// What the remote classifier said about this item (`--online` only, D-063).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semantic: Option<Box<SemanticEvidence>>,
}

/// One classifier decision behind an item (PRD §23.7). The probability is the provider's,
/// unchanged; the broker only compares it with the threshold.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct SemanticEvidence {
    pub stage: crate::online::SemanticStage,
    /// `admitted`, `rejected`, `selected_source`, `reading_lead` or `excluded`.
    pub state: &'static str,
    pub probability: f64,
    pub threshold: f64,
    pub model: String,
    /// `sha256:` of the request that carried the question.
    pub request_digest: String,
    /// The version of the source that was evaluated.
    pub content_hash: String,
    /// One-based inclusive lines of the evaluated block; absent for a whole file.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lines: Option<[u64; 2]>,
    pub cache_hit: bool,
}

/// `provenance.online` (PRD §23.7, D-063).
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct OnlineProvenance {
    pub enabled: bool,
    pub provider: String,
    pub model: String,
    pub requests: usize,
    pub cache_hits: usize,
    pub incomplete: bool,
    /// `complete`, `incomplete`, `interrupted` or `skipped`.
    pub discovery: &'static str,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct TestItem {
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub run: Option<String>,
    pub why_included: String,
    pub source: Source,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Risk {
    pub kind: &'static str,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    pub source: Source,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Limitation {
    pub kind: &'static str,
    pub detail: String,
    pub source: Source,
}

/// A generated architectural note about one module, derived only from included items.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Note {
    /// The directory the note is about (`src`, `src/api`...).
    pub scope: String,
    /// Model output derived from repository text: data, never instructions.
    pub text: Untrusted,
    pub generated: bool,
    pub model: String,
    /// `path#symbol` of the items the note was written from.
    pub derived_from: Vec<String>,
    /// Served from the note cache instead of the model.
    pub cached: bool,
    pub source: Source,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Provenance {
    /// Matches `recent_requests[].request_id` in the status resource (PRD 14.2).
    pub request_id: u64,
    pub upstream_tools: Vec<&'static str>,
    pub workspace: String,
    pub ripwire_version: String,
    pub broker_version: &'static str,
    /// Only on `context_for_task` of a process started with `--online`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub online: Option<OnlineProvenance>,
}

fn is_zero(n: &usize) -> bool {
    *n == 0
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Budget {
    pub requested_tokens: u32,
    pub estimated_tokens: u32,
    pub truncated: bool,
    pub shown: usize,
    pub omitted: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_step: Option<String>,
    /// Tests, risks and notes left out because this session already received them (D-029).
    #[serde(skip_serializing_if = "is_zero")]
    pub already_delivered: usize,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Envelope {
    pub schema_version: &'static str,
    pub tool: &'static str,
    pub status: Status,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intent: Option<Intent>,
    /// Broker inference: a one-line deterministic digest of what follows.
    pub summary: String,
    pub items: Vec<Item>,
    pub tests: Vec<TestItem>,
    pub risks: Vec<Risk>,
    pub limitations: Vec<Limitation>,
    /// Phase 3 notes; omitted when no local model is configured (D-037).
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub notes: Vec<Note>,
    pub provenance: Provenance,
    pub budget: Budget,
}
